# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift

#source 'https://github.com/CocoaPods/Specs.git'
source 'https://git.coding.net/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

target 'RxSwiftTest' do

#网络框架以及ORM层映射框架
pod 'Moya' , '~> 8.0.0-beta.6'
pod 'ObjectMapper', '~> 2.2.2'
pod 'Result', '~> 3.1.0'
pod 'URLNavigator', '~> 1.0.0'
#pod 'Moya/RxSwift'
#编程范式框架
pod 'RxSwift',    '~> 3.0.1'
pod 'RxCocoa',    '~> 3.0.1'
pod 'RxBlocking', '~> 3.0.1'
pod 'RxDataSources', '~> 1.0.0'

end

target 'RxSwiftTestTests' do
    inherit! :search_paths
    pod 'RxBlocking', '~> 3.0.1'
    pod 'RxTests',    '~> 3.0.0-beta.2'
    
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
            config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.10'
            if target.name == "BeeCloud"
                target.build_configurations.each do |config|
                    #                if config.name = "DebugStaging"
                    config.build_settings['ENABLE_BITCODE'] = ['false']
                    #                end
                end
            end
        end
    end
end



